/** @type {import('next').NextConfig} */
const nextConfig = {
  typescript: { ignoreBuildErrors: true },
  images: { unoptimized: true },
  async redirects() {
    return [
      // jewishnewsnow + jewishpropertyreport — finance-jargon slugs cleaned July 2026, 308 to clean slug
      { source: '/article/jewish-news-now/2026-06-19-israeli-music-culture-2026-winners-in-streaming-losers-in-live-performance-reven', destination: '/article/jewish-news-now/2026-06-19-israeli-music-2026-streaming-growth-and-live-performance-squeeze', permanent: true },
      { source: '/article/jewish-news-now/2026-06-20-abraham-accords-2026-trade-surge-demands-portfolio-rebalancing-now', destination: '/article/jewish-news-now/2026-06-20-abraham-accords-2026-israel-gulf-trade-surge', permanent: true },
      { source: '/article/jewish-news-now/2026-06-20-israel-us-trade-pact-2026-regulatory-shift-reshapes-asset-allocation', destination: '/article/jewish-news-now/2026-06-20-israel-us-trade-pact-2026-new-regulatory-shift-explained', permanent: true },
      { source: '/article/jewish-news-now/2026-06-20-juneteenth-jewish-solidarity-2026-capital-flows-to-winners-risk-to-outliers', destination: '/article/jewish-news-now/2026-06-20-juneteenth-jewish-solidarity-2026-shared-history-ongoing-dialogue', permanent: true },
      { source: '/article/jewish-news-now/2026-06-20-kosher-food-industry-2026-winners-in-consolidation-losers-in-small-production', destination: '/article/jewish-news-now/2026-06-20-kosher-food-industry-2026-consolidation-pressures-small-producers', permanent: true },
      { source: '/article/jewish-news-now/2026-06-23-diaspora-portfolio-rebalancing-2026-jewish-investors-shift-47b-from-global-equit', destination: '/article/jewish-news-now/2026-06-23-diaspora-investment-trends-2026-jewish-investors-look-to-israel', permanent: true },
      { source: '/article/jewish-news-now/2026-06-28-israel-october-2026-elections-portfolio-winners-and-losers-emerge', destination: '/article/jewish-news-now/2026-06-28-israel-october-2026-elections-key-issues-and-contenders', permanent: true },
      { source: '/article/jewish-news-now/2026-06-20-jerusalem-luxury-real-estate-market-2026-foreign-capital-surge-reshapes-portfoli', destination: '/article/jewish-news-now/2026-06-20-jerusalem-luxury-real-estate-2026-foreign-buyer-surge', permanent: true },
      { source: '/article/jewish-news-now/2026-06-21-israel-iran-2026-conflict-geographic-divergence-reshapes-global-capital-flows', destination: '/article/jewish-news-now/2026-06-21-israel-iran-2026-how-the-conflict-is-reshaping-the-region', permanent: true },
      { source: '/article/jewish-news-now/2026-06-21-jewish-population-growth-2026-regional-divergence-reshapes-capital-flows', destination: '/article/jewish-news-now/2026-06-21-jewish-population-growth-2026-regional-trends-and-divergence', permanent: true },
      { source: '/article/jewish-news-now/2026-06-22-israel-climate-tech-at-inflection-point-26-gw-renewable-targets-reshape-asset-al', destination: '/article/jewish-news-now/2026-06-22-israel-climate-tech-2026-26-gw-renewable-push', permanent: true },
      { source: '/article/jewish-property-report/2026-06-18-americans-buying-israeli-property-portfolio-allocation-and-foreign-buyer-2026-ru', destination: '/article/jewish-property-report/2026-06-18-americans-buying-israeli-property-foreign-buyer-rules-2026', permanent: true },
      { source: '/article/jewish-property-report/2026-06-18-beer-sheva-property-prices-2026-portfolio-allocation-for-diaspora-investors', destination: '/article/jewish-property-report/2026-06-18-beer-sheva-property-prices-2026-guide-for-diaspora-buyers', permanent: true },
      { source: '/article/jewish-property-report/2026-06-19-israel-real-estate-market-forecast-2026-portfolio-allocation-framework', destination: '/article/jewish-property-report/2026-06-19-israel-real-estate-market-forecast-2026-what-buyers-should-expect', permanent: true },
      { source: '/article/jewish-property-report/2026-06-21-10-year-tax-holiday-for-new-olim-real-estate-winners-losers-2026', destination: '/article/jewish-property-report/2026-06-21-10-year-tax-holiday-for-new-olim-real-estate-2026', permanent: true },
      { source: '/article/jewish-property-report/2026-06-22-renting-vs-buying-israel-2026-portfolio-allocation-inflection', destination: '/article/jewish-property-report/2026-06-22-renting-vs-buying-israel-2026-which-makes-sense', permanent: true },
      { source: '/article/jewish-property-report/2026-06-23-modi-effect-on-israeli-real-estate-prices-2026-winners-and-losers', destination: '/article/jewish-property-report/2026-06-23-modiin-effect-on-israeli-real-estate-prices-2026', permanent: true },
      { source: '/article/jewish-property-report/2026-06-23-tel-aviv-apartment-prices-per-sqm-2026-portfolio-allocation-inflection', destination: '/article/jewish-property-report/2026-06-23-tel-aviv-apartment-prices-per-sqm-2026', permanent: true },
      { source: '/article/jewish-property-report/2026-06-24-beersheva-property-prices-2026-winners-gain-23-while-losers-face-stagnation', destination: '/article/jewish-property-report/2026-06-24-beersheva-property-prices-2026-where-values-are-rising', permanent: true },
      { source: '/article/jewish-property-report/2026-06-24-israel-construction-costs-2026-winners-and-losers-in-labor-led-inflation', destination: '/article/jewish-property-report/2026-06-24-israel-construction-costs-2026-labor-led-inflation', permanent: true },
      { source: '/article/jewish-property-report/2026-06-24-tama-38-termination-regional-winners-and-losers-across-israel-s-urban-renewal-ma', destination: '/article/jewish-property-report/2026-06-24-tama-38-termination-israel-urban-renewal', permanent: true },
      { source: '/article/jewish-property-report/2026-06-26-netanya-real-estate-for-foreigners-2026-winners-gain-5-while-coastal-value-above', destination: '/article/jewish-property-report/2026-06-26-netanya-real-estate-for-foreigners-2026-coastal-value', permanent: true },
      { source: '/article/jewish-property-report/2026-07-01-eilat-real-estate-investment-2026-tourism-rebound-winners-vs-construction-risk-l', destination: '/article/jewish-property-report/2026-07-01-eilat-real-estate-investment-2026-tourism-rebound-vs-construction-risk', permanent: true },
      // AliyaToday — 101 finance-toxic URLs quarantined July 2026, 308 to closest clean guide
      { source: '/article/aliya-today/2026-06-18-idf-service-for-olim-in-2026-regulatory-exemptions-reshaping-immigration-economi', destination: '/article/aliya-today/2026-07-01-how-to-make-aliyah-2026-complete-step-by-step-guide', permanent: true },
      { source: '/article/aliya-today/2026-06-18-israel-security-reality-2026-regional-risk-assessment-for-olim', destination: '/article/aliya-today/2026-07-01-how-to-make-aliyah-2026-complete-step-by-step-guide', permanent: true },
      { source: '/article/aliya-today/2026-06-18-summer-2026-north-american-aliyah-structural-shift-or-seasonal-spike', destination: '/article/aliya-today/2026-07-01-aliyah-from-the-usa-to-israel-the-complete-2026-guide', permanent: true },
      { source: '/article/aliya-today/2026-06-18-white-house-attack-plot-and-israel-portfolio-risk-geopolitical-premium-recalibra', destination: '/article/aliya-today/2026-07-01-how-to-make-aliyah-2026-complete-step-by-step-guide', permanent: true },
      { source: '/article/aliya-today/2026-06-19-arnona-municipal-tax-olim-exemption-2026-vs-2016-comparison', destination: '/article/aliya-today/2026-07-01-best-cities-for-olim-2026-the-complete-comparison-guide', permanent: true },
      { source: '/article/aliya-today/2026-06-19-iran-israel-tensions-explained-for-new-olim-diplomatic-escalation-risk', destination: '/article/aliya-today/2026-07-01-how-to-make-aliyah-2026-complete-step-by-step-guide', permanent: true },
      { source: '/article/aliya-today/2026-06-19-israel-pension-rights-olim-2026-structural-shift-or-temporary-exemption', destination: '/article/aliya-today/2026-07-01-bituach-leumi-for-new-olim-2026-registration-benefits-payment-timeline', permanent: true },
      { source: '/article/aliya-today/2026-06-19-us-israel-friction-over-iran-deal-structural-rupture-or-diplomatic-cycle', destination: '/article/aliya-today/2026-07-01-how-to-make-aliyah-2026-complete-step-by-step-guide', permanent: true },
      { source: '/article/aliya-today/2026-06-19-working-in-israel-as-new-olim-employment-2026-vs-2016-reality-check', destination: '/article/aliya-today/2026-07-01-how-to-make-aliyah-2026-complete-step-by-step-guide', permanent: true },
      { source: '/article/aliya-today/2026-06-20-is-it-safe-to-move-to-israel-in-2026-ceasefire-status-and-security-reality', destination: '/article/aliya-today/2026-07-01-how-to-make-aliyah-2026-complete-step-by-step-guide', permanent: true },
      { source: '/article/aliya-today/2026-06-20-israel-school-system-for-olim-children-62-integration-gap-in-2026', destination: '/article/aliya-today/2026-07-02-israeli-school-registration-2026-5-mistakes-new-olim-make-and-how-to-avoid-them', permanent: true },
      { source: '/article/aliya-today/2026-06-20-nefesh-b-nefesh-vs-jewish-agency-2026-aliyah-market-share-power-shift', destination: '/article/aliya-today/2026-06-17-nbn-grants-2026-how-much-money-nefesh-bnefesh-actually-gives', permanent: true },
      { source: '/article/aliya-today/2026-06-20-north-american-aliyah-summer-2026-2-300-immigrants-economic-reality-emerging', destination: '/article/aliya-today/2026-07-01-aliyah-from-the-usa-to-israel-the-complete-2026-guide', permanent: true },
      { source: '/article/aliya-today/2026-06-20-olim-housing-rights-israel-2026-regional-breakdown-and-capital-allocation-strate', destination: '/article/aliya-today/2026-07-01-best-cities-for-olim-2026-the-complete-comparison-guide', permanent: true },
      { source: '/article/aliya-today/2026-06-20-white-house-attack-plot-pro-israel-officials-who-gains-who-loses', destination: '/article/aliya-today/2026-07-01-how-to-make-aliyah-2026-complete-step-by-step-guide', permanent: true },
      { source: '/article/aliya-today/2026-06-21-absorption-centers-vs-private-rental-structural-shift-in-olim-housing-2026', destination: '/article/aliya-today/2026-07-01-best-cities-for-olim-2026-the-complete-comparison-guide', permanent: true },
      { source: '/article/aliya-today/2026-06-21-aliya-tax-exemptions-2026-new-immigrant-regulatory-framework-updated', destination: '/article/aliya-today/2026-07-02-aliyah-tax-exemptions-2026-the-reporting-requirement-myth-busted', permanent: true },
      { source: '/article/aliya-today/2026-06-21-israel-school-olim-integration-6-hour-weekly-gap-exposes-municipality-funding-in', destination: '/article/aliya-today/2026-07-02-israeli-school-registration-2026-5-mistakes-new-olim-make-and-how-to-avoid-them', permanent: true },
      { source: '/article/aliya-today/2026-06-21-israeli-real-estate-for-olim-permanent-inflection-or-temporary-reset-in-2026', destination: '/article/aliya-today/2026-07-01-best-cities-for-olim-2026-the-complete-comparison-guide', permanent: true },
      { source: '/article/aliya-today/2026-06-21-north-american-olim-destination-markets-2026-regional-settlement-allocation-stra', destination: '/article/aliya-today/2026-07-01-aliyah-from-the-usa-to-israel-the-complete-2026-guide', permanent: true },
      { source: '/article/aliya-today/2026-06-22-aliya-checklist-2026-complete-list-10-year-evolution-vs-2016-baseline', destination: '/article/aliya-today/2026-07-01-how-to-make-aliyah-2026-complete-step-by-step-guide', permanent: true },
      { source: '/article/aliya-today/2026-06-22-arnona-municipal-tax-exemption-for-olim-2026-policy-shift-reshapes-settlement-ec', destination: '/article/aliya-today/2026-07-02-aliyah-tax-exemptions-2026-the-reporting-requirement-myth-busted', permanent: true },
      { source: '/article/aliya-today/2026-06-22-israel-child-benefits-olim-2026-bituach-leumi-automatic-enrollment-shifts-absorp', destination: '/article/aliya-today/2026-07-01-bituach-leumi-for-new-olim-2026-registration-benefits-payment-timeline', permanent: true },
      { source: '/article/aliya-today/2026-06-22-israel-citizenship-rights-olim-law-of-return-evolution-vs-2016-framework', destination: '/article/aliya-today/2026-07-01-how-to-make-aliyah-2026-complete-step-by-step-guide', permanent: true },
      { source: '/article/aliya-today/2026-06-22-israel-s-2026-tax-exemption-for-olim-working-remotely-signals-structural-shift', destination: '/article/aliya-today/2026-07-02-aliyah-tax-exemptions-2026-the-reporting-requirement-myth-busted', permanent: true },
      { source: '/article/aliya-today/2026-06-22-misrad-haklita-first-steps-appointment-scarcity-reveals-absorption-crisis-2026', destination: '/article/aliya-today/2026-07-01-how-to-get-your-teudat-zehut-israeli-id-card-in-2026-complete-timeline', permanent: true },
      { source: '/article/aliya-today/2026-06-22-nefesh-b-nefesh-application-guide-regional-approval-variance-analysis-2026', destination: '/article/aliya-today/2026-06-17-nbn-grants-2026-how-much-money-nefesh-bnefesh-actually-gives', permanent: true },
      { source: '/article/aliya-today/2026-06-22-olim-absorption-center-vs-private-rental-capital-allocation-winners-2026', destination: '/article/aliya-today/2026-07-01-best-cities-for-olim-2026-the-complete-comparison-guide', permanent: true },
      { source: '/article/aliya-today/2026-06-22-south-african-olim-capital-flight-2026-rand-devaluation-reshapes-aliyah-economic', destination: '/article/aliya-today/2026-07-01-aliyah-from-south-africa-to-israel-the-complete-2026-guide', permanent: true },
      { source: '/article/aliya-today/2026-06-23-israel-launches-historic-aliyah-plan-tax-incentives-reshape-olim-absorption-econ', destination: '/article/aliya-today/2026-07-02-aliyah-tax-exemptions-2026-the-reporting-requirement-myth-busted', permanent: true },
      { source: '/article/aliya-today/2026-06-23-israel-lease-contract-guide-english-2026-how-deposit-caps-protect-olim', destination: '/article/aliya-today/2026-07-01-best-cities-for-olim-2026-the-complete-comparison-guide', permanent: true },
      { source: '/article/aliya-today/2026-06-23-israel-s-geopolitical-risk-portfolio-framework-for-aliyah-decision-making', destination: '/article/aliya-today/2026-07-01-how-to-make-aliyah-2026-complete-step-by-step-guide', permanent: true },
      { source: '/article/aliya-today/2026-06-23-israeli-driving-license-conversion-timing-capital-allocation-before-the-one-year', destination: '/article/aliya-today/2026-06-30-israel-driving-license-conversion-for-olim-regional-processing-times-costs-2026', permanent: true },
      { source: '/article/aliya-today/2026-06-23-israeli-guarantor-and-arnona-rules-for-olim-apartments-2016-2026-tightening', destination: '/article/aliya-today/2026-07-01-best-cities-for-olim-2026-the-complete-comparison-guide', permanent: true },
      { source: '/article/aliya-today/2026-06-23-mental-health-services-for-english-speakers-in-israel-2026-vs-2016-access-revolu', destination: '/article/aliya-today/2026-06-14-kupat-holim-choice-2026-which-health-fund-fits-your-oleh-financial-profile', permanent: true },
      { source: '/article/aliya-today/2026-06-23-olim-dental-insurance-80-israeli-payment-rate-exposes-90-day-registration-error', destination: '/article/aliya-today/2026-06-14-kupat-holim-choice-2026-which-health-fund-fits-your-oleh-financial-profile', permanent: true },
      { source: '/article/aliya-today/2026-06-23-south-african-aliyah-2026-rand-weakness-rising-antisemitism-reshape-economic-cal', destination: '/article/aliya-today/2026-07-01-aliyah-from-south-africa-to-israel-the-complete-2026-guide', permanent: true },
      { source: '/article/aliya-today/2026-06-24-israel-10-year-tax-exemption-olim-structural-shift-or-policy-blip-2026', destination: '/article/aliya-today/2026-07-02-aliyah-tax-exemptions-2026-the-reporting-requirement-myth-busted', permanent: true },
      { source: '/article/aliya-today/2026-06-24-israel-child-benefits-olim-2026-payment-gaps-and-exposure-risk', destination: '/article/aliya-today/2026-07-01-bituach-leumi-for-new-olim-2026-registration-benefits-payment-timeline', permanent: true },
      { source: '/article/aliya-today/2026-06-24-israel-work-visa-rights-for-olim-2026-structural-inflection-or-temporary-shift', destination: '/article/aliya-today/2026-07-01-how-to-make-aliyah-2026-complete-step-by-step-guide', permanent: true },
      { source: '/article/aliya-today/2026-06-24-israeli-lease-contracts-english-2026-deposit-cap-enforcement-failures', destination: '/article/aliya-today/2026-07-01-best-cities-for-olim-2026-the-complete-comparison-guide', permanent: true },
      { source: '/article/aliya-today/2026-06-24-kupat-holim-clalit-vs-maccabi-vs-meuhedet-2026-olim-hmo-selection-shifts', destination: '/article/aliya-today/2026-06-14-kupat-holim-choice-2026-which-health-fund-fits-your-oleh-financial-profile', permanent: true },
      { source: '/article/aliya-today/2026-06-24-olim-absorption-centers-2026-policy-shift-away-from-transitional-housing', destination: '/article/aliya-today/2026-07-01-best-cities-for-olim-2026-the-complete-comparison-guide', permanent: true },
      { source: '/article/aliya-today/2026-06-24-returning-israelis-2026-renunciation-reversal-and-restored-citizenship-economics', destination: '/article/aliya-today/2026-07-01-how-to-make-aliyah-2026-complete-step-by-step-guide', permanent: true },
      { source: '/article/aliya-today/2026-06-24-start-business-israel-as-oleh-2026-tax-driven-portfolio-calculus', destination: '/article/aliya-today/2026-07-01-how-to-make-aliyah-2026-complete-step-by-step-guide', permanent: true },
      { source: '/article/aliya-today/2026-06-24-tel-aviv-arnona-50-cap-for-olim-reshapes-guarantor-economics-2026', destination: '/article/aliya-today/2026-07-01-best-cities-for-olim-2026-the-complete-comparison-guide', permanent: true },
      { source: '/article/aliya-today/2026-06-25-north-american-jewish-aliyah-surge-june-2026-2-300-immigrants-reshape-diaspora-e', destination: '/article/aliya-today/2026-07-01-aliyah-from-the-usa-to-israel-the-complete-2026-guide', permanent: true },
      { source: '/article/aliya-today/2026-06-26-foreign-company-permanent-establishment-the-hidden-risk-for-oleh-entrepreneurs-2', destination: '/article/aliya-today/2026-07-01-how-to-make-aliyah-2026-complete-step-by-step-guide', permanent: true },
      { source: '/article/aliya-today/2026-06-26-israel-customs-free-import-list-2026-a-decade-of-tightening-rules-for-olim', destination: '/article/aliya-today/2026-06-22-cost-of-making-aliyah-2026-complete-budget-for-single-couple-family-olim', permanent: true },
      { source: '/article/aliya-today/2026-06-26-israel-social-security-number-for-olim-portfolio-timing-and-asset-id-risk', destination: '/article/aliya-today/2026-07-01-bituach-leumi-for-new-olim-2026-registration-benefits-payment-timeline', permanent: true },
      { source: '/article/aliya-today/2026-06-26-misrad-hapnim-appointment-capacity-2026-structural-shift-or-bureaucratic-collaps', destination: '/article/aliya-today/2026-07-01-how-to-get-your-teudat-zehut-israeli-id-card-in-2026-complete-timeline', permanent: true },
      { source: '/article/aliya-today/2026-06-26-north-american-aliyah-2026-2-300-immigrants-reshape-portfolio-allocation-strateg', destination: '/article/aliya-today/2026-07-01-aliyah-from-the-usa-to-israel-the-complete-2026-guide', permanent: true },
      { source: '/article/aliya-today/2026-06-26-working-in-israel-as-new-olim-2026-regional-employment-reality', destination: '/article/aliya-today/2026-07-01-how-to-make-aliyah-2026-complete-step-by-step-guide', permanent: true },
      { source: '/article/aliya-today/2026-06-28-israel-army-service-for-olim-2026-financial-winners-losers-decoded', destination: '/article/aliya-today/2026-07-01-how-to-make-aliyah-2026-complete-step-by-step-guide', permanent: true },
      { source: '/article/aliya-today/2026-06-28-israel-electricity-gas-utilities-setup-2026-structural-reform-inflection-or-temp', destination: '/article/aliya-today/2026-06-22-cost-of-making-aliyah-2026-complete-budget-for-single-couple-family-olim', permanent: true },
      { source: '/article/aliya-today/2026-06-28-israeli-mobile-phone-plans-2026-regulatory-price-floor-for-new-olim', destination: '/article/aliya-today/2026-06-22-cost-of-making-aliyah-2026-complete-budget-for-single-couple-family-olim', permanent: true },
      { source: '/article/aliya-today/2026-06-28-school-system-capacity-crunch-olim-children-and-the-integration-bottleneck-2026', destination: '/article/aliya-today/2026-07-02-israeli-school-registration-2026-5-mistakes-new-olim-make-and-how-to-avoid-them', permanent: true },
      { source: '/article/aliya-today/2026-06-28-with-massive-regional-price-variation-across-israel-s-supermarket-chains-and-mar', destination: '/article/aliya-today/2026-07-01-how-to-make-aliyah-2026-complete-step-by-step-guide', permanent: true },
      { source: '/article/aliya-today/2026-06-29-aliyah-of-renewal-2026-france-s-350-antisemitism-surge-triggers-israel-policy-ov', destination: '/article/aliya-today/2026-07-01-aliyah-from-france-to-israel-the-complete-2026-guide', permanent: true },
      { source: '/article/aliya-today/2026-06-29-israel-driving-test-english-conversion-5-year-window-regulatory-risk-2026', destination: '/article/aliya-today/2026-06-30-israel-driving-license-conversion-for-olim-regional-processing-times-costs-2026', permanent: true },
      { source: '/article/aliya-today/2026-06-29-israel-school-system-capacity-2026-regional-breakdown-for-olim-children', destination: '/article/aliya-today/2026-07-02-israeli-school-registration-2026-5-mistakes-new-olim-make-and-how-to-avoid-them', permanent: true },
      { source: '/article/aliya-today/2026-06-29-israeli-culture-shock-for-olim-regional-adaptation-economics-2026', destination: '/article/aliya-today/2026-07-02-israeli-school-registration-2026-5-mistakes-new-olim-make-and-how-to-avoid-them', permanent: true },
      { source: '/article/aliya-today/2026-06-29-western-aliyah-surge-2025-8-000-olim-reshape-israel-s-workforce-demographics', destination: '/article/aliya-today/2026-07-01-how-to-make-aliyah-2026-complete-step-by-step-guide', permanent: true },
      { source: '/article/aliya-today/2026-06-30-arnona-exemption-2026-how-olim-avoid-70-90-municipal-tax-for-first-year', destination: '/article/aliya-today/2026-07-01-best-cities-for-olim-2026-the-complete-comparison-guide', permanent: true },
      { source: '/article/aliya-today/2026-07-01-21-900-olim-made-aliyah-in-2025-how-singles-couples-and-families-navigate-immigr', destination: '/article/aliya-today/2026-07-01-how-to-make-aliyah-2026-complete-step-by-step-guide', permanent: true },
      { source: '/article/aliya-today/2026-07-01-aliyah-from-uk-to-israel-2026-family-financial-planning-guide', destination: '/article/aliya-today/2026-07-01-aliyah-from-the-uk-to-israel-the-complete-2026-guide', permanent: true },
      { source: '/article/aliya-today/2026-07-01-aliyah-tax-exemptions-2026-a-decade-of-declining-benefits', destination: '/article/aliya-today/2026-07-02-aliyah-tax-exemptions-2026-the-reporting-requirement-myth-busted', permanent: true },
      { source: '/article/aliya-today/2026-07-01-first-week-in-israel-aliyah-banking-tax-and-residency-checklist', destination: '/article/aliya-today/2026-07-02-first-week-in-israel-aliyah-2026-the-real-priority-sequence-not-what-most-olim-d', permanent: true },
      { source: '/article/aliya-today/2026-07-01-usa-to-israel-aliyah-2026-the-real-18-month-timeline', destination: '/article/aliya-today/2026-07-01-aliyah-from-the-usa-to-israel-the-complete-2026-guide', permanent: true },
      // AliyaToday — duplicate/renamed articles consolidated during content
      // cleanup (July 2026). Each old slug 301s to its canonical replacement
      // so no previously-indexed or shared URL 404s.
      {
        source: '/article/aliya-today/2026-07-01-cost-of-living-in-israel-2026-realistic-monthly-budget-for-n',
        destination: '/article/aliya-today/2026-07-01-cost-of-living-in-israel-2026-what-new-olim-actually-spend-p',
        permanent: true,
      },
      {
        source: '/article/aliya-today/2026-07-01-bituach-leumi-for-new-olim-2026-registration-steps-and-benef',
        destination: '/article/aliya-today/2026-07-01-bituach-leumi-for-new-olim-2026-registration-benefits-payment-timeline',
        permanent: true,
      },
      {
        source: '/article/aliya-today/2026-06-23-sal-klita-benefits-2026-how-much-olim-actually-receive',
        destination: '/article/aliya-today/2026-06-22-sal-klita-2026-the-complete-guide',
        permanent: true,
      },
      {
        source: '/article/aliya-today/2026-06-28-sal-klita-2026-how-much-money-new-olim-receive',
        destination: '/article/aliya-today/2026-06-22-sal-klita-2026-the-complete-guide',
        permanent: true,
      },
      {
        source: '/article/aliya-today/2026-06-22-cost-of-making-aliyah-2026-financial-breakdown-vs-2016-baseline',
        destination: '/article/aliya-today/2026-06-22-cost-of-making-aliyah-2026-complete-budget-for-single-couple-family-olim',
        permanent: true,
      },
      {
        source: '/article/aliya-today/2026-07-01-israeli-politics-coalition-risk-knesset-navigation-for-investor-olim',
        destination: '/article/aliya-today/2026-07-01-how-to-make-aliyah-2026-complete-step-by-step-guide',
        permanent: true,
      },
      {
        source: '/article/aliya-today/2026-06-24-how-much-money-do-you-need-to-make-aliyah-2026-financial-winners-losers-decoded',
        destination: '/article/aliya-today/2026-06-22-cost-of-making-aliyah-2026-complete-budget-for-single-couple-family-olim',
        permanent: true,
      },
      {
        source: '/article/aliya-today/2026-06-24-how-much-money-do-i-need-to-make-aliyah-the-2026-financial-roadmap',
        destination: '/article/aliya-today/2026-06-22-cost-of-making-aliyah-2026-complete-budget-for-single-couple-family-olim',
        permanent: true,
      },
      {
        source: '/article/aliya-today/2026-06-15-aliyah-cost-breakdown-2026-pre-arrival-to-month-six',
        destination: '/article/aliya-today/2026-06-22-cost-of-making-aliyah-2026-complete-budget-for-single-couple-family-olim',
        permanent: true,
      },
      {
        source: '/article/aliya-today/2026-06-21-bituach-leumi-for-olim-2026-how-social-security-changed-since-2016',
        destination: '/article/aliya-today/2026-07-01-bituach-leumi-for-new-olim-2026-registration-benefits-payment-timeline',
        permanent: true,
      },
      {
        source: '/article/aliya-today/2026-06-30-israel-driving-test-english-conversion-2026-regulatory-inflection-or-temporary-p',
        destination: '/article/aliya-today/2026-06-17-free-ulpan-for-new-olim-2026-how-to-enrol',
        permanent: true,
      },
      {
        source: '/article/aliya-today/2026-07-01-israeli-bank-account-new-olim-2026-which-bank-how-to-open',
        destination: '/article/aliya-today/2026-06-17-how-to-open-an-israeli-bank-account-as-a-new-oleh-2026',
        permanent: true,
      },
      {
        source: '/article/aliya-today/2026-06-23-israeli-bank-accounts-for-olim-2026-vs-2016-access-revolution',
        destination: '/article/aliya-today/2026-06-17-how-to-open-an-israeli-bank-account-as-a-new-oleh-2026',
        permanent: true,
      },
      {
        source: '/article/aliya-today/2026-06-26-kupat-holim-2026-which-health-fund-new-olim-choose',
        destination: '/article/aliya-today/2026-06-14-kupat-holim-choice-2026-which-health-fund-fits-your-oleh-financial-profile',
        permanent: true,
      },
      {
        source: '/article/aliya-today/2026-06-17-converting-your-foreign-driving-licence-to-israeli-2026',
        destination: '/article/aliya-today/2026-06-30-israel-driving-license-conversion-for-olim-regional-processing-times-costs-2026',
        permanent: true,
      },
      {
        source: '/article/aliya-today/2026-06-24-teudat-zehut-processing-overhaul-2026-olim-documentation-bottleneck',
        destination: '/article/aliya-today/2026-07-01-how-to-get-your-teudat-zehut-israeli-id-card-in-2026-complete-timeline',
        permanent: true,
      },
      {
        source: '/article/aliya-today/2026-06-29-usa-to-israel-aliyah-process-2026-financial-compliance-framework-for-olim',
        destination: '/article/aliya-today/2026-07-01-aliyah-from-the-usa-to-israel-the-complete-2026-guide',
        permanent: true,
      },
      {
        source: '/article/aliya-today/2026-06-23-uk-to-israel-aliyah-2026-currency-risk-and-tax-trap-exposure',
        destination: '/article/aliya-today/2026-07-01-aliyah-from-the-uk-to-israel-the-complete-2026-guide',
        permanent: true,
      },
      {
        source: '/article/aliya-today/2026-06-19-uk-aliyah-to-israel-2026-tax-compliance-and-currency-risk-management',
        destination: '/article/aliya-today/2026-07-01-aliyah-from-the-uk-to-israel-the-complete-2026-guide',
        permanent: true,
      },
      {
        source: '/article/aliya-today/2026-06-23-usa-olim-aliyah-process-2026-financial-winners-and-losers-mapped',
        destination: '/article/aliya-today/2026-07-01-aliyah-from-the-usa-to-israel-the-complete-2026-guide',
        permanent: true,
      },
      {
        source: '/article/aliya-today/2026-06-21-french-aliyah-2026-economic-winners-and-losers-emerge',
        destination: '/article/aliya-today/2026-07-01-aliyah-from-france-to-israel-the-complete-2026-guide',
        permanent: true,
      },
      {
        source: '/article/aliya-today/2026-06-21-pre-aliyah-hebrew-learning-portfolio-allocation-strategy-for-language-investment',
        destination: '/article/aliya-today/2026-06-17-free-ulpan-for-new-olim-2026-how-to-enrol',
        permanent: true,
      },
      {
        source: '/article/aliya-today/2026-06-19-hebrew-learning-before-aliyah-structural-shift-or-seasonal-necessity-2026',
        destination: '/article/aliya-today/2026-06-17-free-ulpan-for-new-olim-2026-how-to-enrol',
        permanent: true,
      },
      {
        source: '/article/aliya-today/2026-06-28-best-ulpan-programs-2026-cost-benefit-analysis-for-winners-and-losers',
        destination: '/article/aliya-today/2026-06-17-free-ulpan-for-new-olim-2026-how-to-enrol',
        permanent: true,
      },
      {
        source: '/article/aliya-today/2026-06-21-free-ulpan-registration-israel-4-risk-exposures-olim-miss',
        destination: '/article/aliya-today/2026-06-17-free-ulpan-for-new-olim-2026-how-to-enrol',
        permanent: true,
      },
      {
        source: '/article/aliya-today/2026-06-26-teudat-zehut-processing-delays-portfolio-implications-for-2026-olim',
        destination: '/article/aliya-today/2026-07-01-how-to-get-your-teudat-zehut-israeli-id-card-in-2026-complete-timeline',
        permanent: true,
      },
      {
        source: '/article/aliya-today/2026-06-22-israeli-driving-license-conversion-olim-temporary-friction-or-structural-inflect',
        destination: '/article/aliya-today/2026-06-30-israel-driving-license-conversion-for-olim-regional-processing-times-costs-2026',
        permanent: true,
      },
      {
        source: '/article/aliya-today/2026-06-21-israeli-driving-license-conversion-olim-portfolio-timing-and-financial-implicati',
        destination: '/article/aliya-today/2026-06-30-israel-driving-license-conversion-for-olim-regional-processing-times-costs-2026',
        permanent: true,
      },
      {
        source: '/article/aliya-today/2026-07-01-israeli-driving-license-conversion-structural-shift-toward-expedited-integration',
        destination: '/article/aliya-today/2026-06-30-israel-driving-license-conversion-for-olim-regional-processing-times-costs-2026',
        permanent: true,
      },
      {
        source: '/article/aliya-today/2026-06-21-kupat-holim-for-olim-2026-portfolio-allocation-and-healthcare-cost-reality',
        destination: '/article/aliya-today/2026-06-14-kupat-holim-choice-2026-which-health-fund-fits-your-oleh-financial-profile',
        permanent: true,
      },
      {
        source: '/article/aliya-today/2026-06-23-kupat-holim-for-olim-2026-regional-winners-across-israel-s-health-systems',
        destination: '/article/aliya-today/2026-06-14-kupat-holim-choice-2026-which-health-fund-fits-your-oleh-financial-profile',
        permanent: true,
      },
      {
        source: '/article/aliya-today/2026-06-20-israel-bank-account-for-olim-winners-losers-2026-integration-costs',
        destination: '/article/aliya-today/2026-06-17-how-to-open-an-israeli-bank-account-as-a-new-oleh-2026',
        permanent: true,
      },
      {
        source: '/article/aliya-today/2026-06-19-french-aliyah-to-israel-2026-asset-allocation-signals-in-western-migration-surge',
        destination: '/article/aliya-today/2026-07-01-aliyah-from-france-to-israel-the-complete-2026-guide',
        permanent: true,
      },
      {
        source: '/article/aliya-today/2026-06-18-french-aliyah-to-israel-2026-inflection-point-or-cyclical-spike',
        destination: '/article/aliya-today/2026-07-01-aliyah-from-france-to-israel-the-complete-2026-guide',
        permanent: true,
      },
      {
        source: '/article/aliya-today/2026-06-22-french-aliyah-2026-inflection-point-or-cyclical-surge',
        destination: '/article/aliya-today/2026-07-01-aliyah-from-france-to-israel-the-complete-2026-guide',
        permanent: true,
      },
      {
        source: '/article/aliya-today/2026-06-18-south-african-aliyah-2026-portfolio-rebalancing-for-emerging-israeli-residents',
        destination: '/article/aliya-today/2026-07-01-aliyah-from-south-africa-to-israel-the-complete-2026-guide',
        permanent: true,
      },
      {
        source: '/article/aliya-today/2026-06-20-first-week-in-israel-risk-exposure-for-new-olim-2026',
        destination: '/article/aliya-today/2026-06-19-first-week-in-israel-aliyah-regional-execution-playbook-2026',
        permanent: true,
      },
      {
        source: '/article/aliya-today/2026-06-14-aliyah-checklist-2026-disclosure-timeline-splits-winners-losers',
        destination: '/article/aliya-today/2026-07-01-how-to-make-aliyah-2026-complete-step-by-step-guide',
        permanent: true,
      },
      {
        source: '/article/aliya-today/2026-06-21-aliyah-step-by-step-2026-hidden-risk-exposure-in-documentation-financial-and-com',
        destination: '/article/aliya-today/2026-07-01-how-to-make-aliyah-2026-complete-step-by-step-guide',
        permanent: true,
      },
      {
        source: '/article/aliya-today/2026-06-18-hebrew-learning-before-aliyah-how-2026-compares-to-2016',
        destination: '/article/aliya-today/2026-06-17-free-ulpan-for-new-olim-2026-how-to-enrol',
        permanent: true,
      },
    ]
  },
  async headers() {
    return [
      {
        source: '/api/:path*',
        headers: [
          { key: 'Access-Control-Allow-Origin', value: '*' },
          { key: 'Access-Control-Allow-Methods', value: 'GET,POST,OPTIONS' },
          { key: 'Access-Control-Allow-Headers', value: 'Content-Type,Authorization' },
        ],
      },
    ]
  },
}
export default nextConfig
